### ISSUE TITLE
Multiple Apps with the same name and version added to the Teams Developer Portal

### ISSUE THREAD

**Issue by thomyg** [OfficeDev/TeamsFx#1273]
**Describe the bug**
I assume by clicking on the Configure SSO wizard multiple times, I managed to end up with five Apps with the same name in the Teams Developer Portal. Those apps all reference the same Azure AD app, and there is only one app inside of Azure. It looks like to be a Teams app issue only. They all are the same but have different Teams app IDs.  

**To Reproduce**
Creating a project and configuring SSO multiple times.

**Expected behavior**
Only one app in the Teams Developer Dashboard with the same name. 

**Screenshots**
![image](https://user-images.githubusercontent.com/10920072/120486189-185a4c80-c3b5-11eb-852b-e2128699012c.png)

**Comment by therealjohn** [comment]
@thomyg Thanks for reporting this. It does seem like we have a bug here. 

Why were you clicking Configure for SSO multiple times? I'd like to better understand what you were trying to do and see if we need to rethink how this works. Thanks!

**Comment by thomyg** [comment]
hi @therealjohn!

 It's related to this [scenario](https://github.com/OfficeDev/TeamsFx/issues/1247). 

I have multiple accounts in Visual Studio that are connected to different tenants. I clicked on "Configure for SSO", the auth pop up opened and closed immediately. Leaving me with no clue about the tenant used in the wizard. That's why I clicked there multiple times as I wanted to find out what account was used and in which tenant die Azure AD app got deployed.

**Comment by therealjohn** [comment]
Thank you for the context - that makes sense! 

Right now we don't provide a good way to configure exactly which accounts are used after a successful login - the toolkit re-uses the previous selected account if it can. We have it in our backlog to improve this. 

For the other issue you linked, we'll add some info to the output so it's clearer which account was used.

**Comment by therealjohn** [comment]
This is now fixed in 0.1.48.43394 available on the Marketplace.

**Comment by creage** [comment]
@therealjohn Could you please provide a link to the fixed version? As the latest available version on Marketplace is [2.0.1](https://marketplace.visualstudio.com/items?itemName=TeamsDevApp.ms-teams-vscode-extension). And whenever I start the debugging by hitting F5 in VSCode - I still receive a new app registration in my AzureAD.

**Comment by therealjohn** [comment]
@creage Sorry for the confusion. This issue is for the Visual Studio extension, not VS Code extension. 

VS: https://marketplace.visualstudio.com/items?itemName=msft-vsteamstoolkit.vsteamstoolkit
VS Code: https://marketplace.visualstudio.com/items?itemName=TeamsDevApp.ms-teams-vscode-extension

**Comment by thomyg** [comment]
@therealjohn -> thx, I'm happy to confirm the fix! And an additional "Thank you" for the added output, indicating the SSO support for my app!

![image](https://user-images.githubusercontent.com/10920072/121401102-a0fa5f00-c958-11eb-88a1-3ab4fabc463a.png)
