### ISSUE TITLE
Asking to add the app twice for local debug

### ISSUE THREAD

**Issue by amansani15** [OfficeDev/TeamsFx#7411]
**Describe the bug**
I am running my teams app locally and it opens in the edge browser. Gives me a popup to add the application and test it. After I click on **Add** button in the popup, the popup doesn't go away but loads the app in the background. I have to hit the add button again then the popup closes after the second time or I need to close the popup by using close button manually

**Expected behavior**
I want to add the app only once and the popup should close after the first attempt itself.

**Screenshots**
![image](https://user-images.githubusercontent.com/62998123/210852279-e170967b-bcef-49eb-9f0e-a848a2600248.png)

**VS Code Extension Information (please complete the following information):**
OS: Windows 10 Pro
VS Code Version 1.72.0
Teams tool kit version: V4.2.1

Any inputs are highly appreciated. Thank you

**Comment by rijinSan** [comment]
I am also getting same issue in local debug, please prioritize fixing this issue

**Comment by IvanJobs** [comment]
Hi @amansani15 @rijinSan, It's a known issue caused by the upstream team and thanks for reporting this issue to us.
We've connected with the upstream team last week and also created an incident ticket for them. They are actively working on it and once it's mitigated, can @kuojianlu post a message here to notify TTK's customers here since you're tracking the ticket now? Thanks.

**Comment by kuojianlu** [comment]
@IvanJobs Sure.

**Comment by amansani15** [comment]
Thank you, looking forward for the fix.

**Comment by kuojianlu** [comment]
@amansani15 Please note that this bug has been fixed.

**Comment by amansani15** [comment]
Hello @kuojianlu, thanks for fixing the bug. Do we need to update to any new version or what exactly the steps we need to take at our end to not to see the bug?

**Comment by kuojianlu** [comment]
@amansani15 The fix is in Teams not Teams Toolkit, so you do not need to update Teams Toolkit. The fix will take effect automatically.

**Comment by amansani15** [comment]
Oh okay, good to know. However I still see that issue at my end though. May I know when the fix will take effect at our end? @kuojianlu

**Comment by kuojianlu** [comment]
@amansani15 It's expected to be totally rolled out to public in couple days.

**Comment by amansani15** [comment]
Awesome, looking forward to it. Thank you
